---
language: generic

sudo: required

services:
  - docker

install:
  - docker --version

script:
  - IMAGE="nolith/ansible-test" VERSION="ubuntu_14.04" ./tests/utils/run_test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
