---
language: python
python: "2.7"

sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible
  # Check ansible version
  - ansible --version
  - mkdir -p group_vars
  - "printf 'docker_users: [ travis ]' > group_vars/all"

script:
  - ansible-playbook tests/test.yml -i tests/inventory -c local --syntax-check
  - ansible-playbook -v tests/test.yml -i tests/inventory -c local
  - docker --version
  - sudo -E su $USER -c 'docker run -it alpine echo "Hello World!"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
